# Generated by Django 5.0 on 2023-12-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptos', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scuser',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like_cryptos', to='cryptos.crypto'),
        ),
        migrations.AddField(
            model_name='scuser',
            name='subscribes',
            field=models.ManyToManyField(blank=True, related_name='sub_cryptos', to='cryptos.crypto'),
        ),
    ]
