# Generated by Django 5.0 on 2023-12-11 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(null=True, upload_to='cryptos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('volume', models.FloatField(default=0.0)),
                ('circulating_supply', models.FloatField(default=0.0)),
                ('market_cap', models.FloatField(default=0.0)),
                ('transactions_count', models.IntegerField(default=0)),
                ('current_price', models.FloatField()),
            ],
            options={
                'verbose_name': 'CryptoCurrency',
                'verbose_name_plural': 'CryptoCurrencies',
            },
        ),
        migrations.CreateModel(
            name='CryptoNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='news/')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CrytoPricePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('price', models.FloatField()),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptos.crypto')),
            ],
        ),
    ]
